### ISSUE TITLE
difficult to override styles

### ISSUE THREAD

**Issue by devinholloway** [Bastorx/reactjs-coverflow#11] opened 2016-10-28 00:05 UTC
I was attempting to change the styles a bit. In particular, I wanted to mess with the perspective styles, but I found it a bit difficult to do so (without modifying your source). I was trying to do this by linking in a CSS file in my document's head. The problem was, my styles had no effect because your component is injecting a bunch of styles directly into the head, and they get injected after any css document linking already in the head.

I got around this by setting the code:
Coverflow.cssLoaded=true;
in my wrapper shortly after importing the Coverflow component.  This prevents _loadCSS() from injecting those styles. The only thing, then, was I need to be sure to include all styles in my css document, not just the ones I wanted to override. It would be nice if this could be handled a bit differently. Or am I going about overriding styles the wrong way?

Other than that, I'm really liking this so far. I especially like the ability to specify custom dimensions for the images and the component still works as expected (this is not possible in the other react coverflow). I'll be looking foward to the IE fixes too.

**Comment by Bastorx** [comment] 2016-10-28 11:30
Thanks for your comment about this module :)

I will continue to work to this project this evening (UTC+2 timezone). And I will push a new version with the IE fix.

I understand your problem to overwritte the css,  "temporaly" if you want to overwritte my css more easier put the flag !important, but I will take your issue seriously and I will fix this problem :)

The project will be refactoring to ES6.

I can purpose you to work on my code and purpose a merge request if you want

In all case, I will work on this issue after fix IE problem.

**Comment by devinholloway** [comment] 2016-10-28 17:17
Good call with the !important flag. I hadn't thought of that

**Comment by Bastorx** [comment] 2016-10-29 17:09
Ok I find the problem, I use appendChild to insert my style in your document.head
The problem is that my css is insered in the end of <head> child element, so it is priority.

I use beforeInsert and no appendChild it fix this problem.

I will deploy a new version of this package soon, with all fix and the refactoring.

ClassName will be updated in this new version so I will give a major version and go directly to 1.0.0

**Comment by devinholloway** [comment] 2016-10-29 18:15
Great, thanks!

**Comment by Bastorx** [comment] 2016-10-29 20:16
Fixed in version 1.0.0

**Closed by Bastorx** 2016-10-29 20:16 UTC
